// Generated by CoffeeScript 1.7.1
(function() {
  var HTTPServer, RequestHandler, http_server;

  RequestHandler = (function() {
    function RequestHandler() {}

    RequestHandler.hello = function(request, response) {
      response.writeHead(200, {
        "Content-Type": "text/plain"
      });
      response.write("nodejs webserver running");
      return response.end();
    };

    return RequestHandler;

  })();

  HTTPServer = (function() {
    function HTTPServer(port) {
      this.http = require('http');
      this.port = port;
      this.server = this.create_server();
    }

    HTTPServer.prototype.create_server = function() {
      return this.http.createServer(RequestHandler.hello);
    };

    HTTPServer.prototype.start = function() {
      return this.server.listen(this.port);
    };

    return HTTPServer;

  })();

  http_server = new HTTPServer(8888);

  http_server.start();

}).call(this);
